CREATE DATABASE IF NOT EXISTS foolproof_exam CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE foolproof_exam;
CREATE USER IF NOT EXISTS 'foolproof_admin'@'localhost' IDENTIFIED BY 'FoolProof@2026!';
GRANT ALL PRIVILEGES ON foolproof_exam.* TO 'foolproof_admin'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(120) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('ADMIN','AUTHORITY','PROCTOR','EVALUATOR','CANDIDATE','REVIEWER') NOT NULL,
  full_name VARCHAR(180) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS exams (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(64) NOT NULL UNIQUE,
  title VARCHAR(220) NOT NULL,
  duration_minutes INT NOT NULL,
  total_marks DECIMAL(10,2) NOT NULL,
  scheduled_start DATETIME NOT NULL,
  scheduled_end DATETIME NOT NULL,
  status ENUM('DRAFT','SCHEDULED','RUNNING','CLOSED','RESULTS_PENDING','PUBLISHED') NOT NULL DEFAULT 'DRAFT',
  assurance_level ENUM('STANDARD','HIGH','CRITICAL') NOT NULL DEFAULT 'CRITICAL',
  offline_resilient TINYINT(1) NOT NULL DEFAULT 1,
  version_no INT NOT NULL DEFAULT 1,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS questions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  exam_id BIGINT UNSIGNED NOT NULL,
  question_no INT NOT NULL,
  prompt TEXT NOT NULL,
  option_a VARCHAR(500) NOT NULL,
  option_b VARCHAR(500) NOT NULL,
  option_c VARCHAR(500) NOT NULL,
  option_d VARCHAR(500) NOT NULL,
  correct_option CHAR(1) NOT NULL,
  marks DECIMAL(8,2) NOT NULL DEFAULT 1,
  topic VARCHAR(120) NOT NULL,
  difficulty ENUM('EASY','MEDIUM','HARD') NOT NULL DEFAULT 'MEDIUM',
  version_no INT NOT NULL DEFAULT 1,
  approved TINYINT(1) NOT NULL DEFAULT 1,
  FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
  UNIQUE KEY uq_exam_qno (exam_id, question_no)
);

CREATE TABLE IF NOT EXISTS enrollments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  exam_id BIGINT UNSIGNED NOT NULL,
  candidate_id BIGINT UNSIGNED NOT NULL,
  enrollment_status ENUM('INVITED','READY','STARTED','SUBMITTED','REVIEW','EVALUATED','RESULT_PUBLISHED') NOT NULL DEFAULT 'INVITED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
  FOREIGN KEY (candidate_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uq_enrollment (exam_id, candidate_id)
);

CREATE TABLE IF NOT EXISTS attempts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  exam_id BIGINT UNSIGNED NOT NULL,
  candidate_id BIGINT UNSIGNED NOT NULL,
  session_uuid CHAR(36) NOT NULL UNIQUE,
  status ENUM('READY','ACTIVE','OFFLINE','RECONNECTING','SUBMITTED','REVIEW','EVALUATION','RESULT_READY') NOT NULL DEFAULT 'READY',
  started_at DATETIME NULL,
  submitted_at DATETIME NULL,
  last_server_sync DATETIME NULL,
  submission_hash VARCHAR(128) NULL,
  score DECIMAL(10,2) NULL,
  FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
  FOREIGN KEY (candidate_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS answers (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  attempt_id BIGINT UNSIGNED NOT NULL,
  question_id BIGINT UNSIGNED NOT NULL,
  selected_option CHAR(1) NULL,
  time_spent_seconds INT NOT NULL DEFAULT 0,
  screen_facing_seconds INT NOT NULL DEFAULT 0,
  looking_down_seconds INT NOT NULL DEFAULT 0,
  last_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
  FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE,
  UNIQUE KEY uq_attempt_question (attempt_id, question_id)
);

CREATE TABLE IF NOT EXISTS integrity_events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  attempt_id BIGINT UNSIGNED NOT NULL,
  event_type VARCHAR(80) NOT NULL,
  severity ENUM('INFO','TECHNICAL','ANOMALY','VIOLATION') NOT NULL DEFAULT 'INFO',
  question_id BIGINT UNSIGNED NULL,
  description VARCHAR(1000) NOT NULL,
  confidence DECIMAL(5,4) NULL,
  evidence_ref VARCHAR(255) NULL,
  occurred_at DATETIME NOT NULL,
  prev_hash VARCHAR(128) NULL,
  event_hash VARCHAR(128) NOT NULL,
  FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
  FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS evaluations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  attempt_id BIGINT UNSIGNED NOT NULL UNIQUE,
  evaluator_id BIGINT UNSIGNED NULL,
  auto_score DECIMAL(10,2) NOT NULL DEFAULT 0,
  final_score DECIMAL(10,2) NULL,
  status ENUM('PENDING','EVALUATED','MODERATED') NOT NULL DEFAULT 'PENDING',
  notes TEXT NULL,
  evaluated_at DATETIME NULL,
  FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
  FOREIGN KEY (evaluator_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS appeals (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  attempt_id BIGINT UNSIGNED NOT NULL,
  candidate_id BIGINT UNSIGNED NOT NULL,
  category VARCHAR(120) NOT NULL,
  description TEXT NOT NULL,
  status ENUM('OPEN','UNDER_REVIEW','ACCEPTED','REJECTED') NOT NULL DEFAULT 'OPEN',
  reviewer_notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (attempt_id) REFERENCES attempts(id) ON DELETE CASCADE,
  FOREIGN KEY (candidate_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  actor_user_id BIGINT UNSIGNED NULL,
  action VARCHAR(120) NOT NULL,
  entity_type VARCHAR(80) NOT NULL,
  entity_id VARCHAR(80) NULL,
  metadata_json JSON NULL,
  prev_hash VARCHAR(128) NULL,
  event_hash VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
);
