import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ShieldCheck,Sun,Moon,LayoutDashboard,BookOpen,Users,Activity,FileText,LogOut,LockKeyhole,Wifi,WifiOff,MonitorCheck,Eye,Clock3,AlertTriangle,CheckCircle2,Download,Search,ChevronRight,ServerCog} from 'lucide-react';
import './styles.css';

const API=localStorage.getItem('fp_api')||import.meta.env.VITE_API_URL||'/api';
async function api(path,opts={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});let d={};try{d=await r.json()}catch{} if(!r.ok)throw new Error(d.error||'Request failed');return d;}

function App(){
 const [theme,setTheme]=useState(localStorage.getItem('fp_theme')||'dark');
 const [session,setSession]=useState(()=>JSON.parse(localStorage.getItem('fp_session')||'null'));
 const [page,setPage]=useState('overview');
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('fp_theme',theme)},[theme]);
 if(!session) return <Login onLogin={s=>{localStorage.setItem('fp_session',JSON.stringify(s));setSession(s)}} theme={theme} setTheme={setTheme}/>;
 return <div className="app-shell"><Sidebar session={session} page={page} setPage={setPage} logout={()=>{localStorage.removeItem('fp_session');setSession(null)}} theme={theme} setTheme={setTheme}/><main className="main"><Topbar session={session} theme={theme} setTheme={setTheme}/>{session.user.role==='CANDIDATE'?<CandidateHome session={session} page={page} setPage={setPage}/>:session.user.role==='PROCTOR'||session.user.role==='REVIEWER'?<ProctorHome session={session} page={page}/>:session.user.role==='EVALUATOR'?<EvaluatorHome session={session} page={page}/>:<AdminAuthorityHome session={session} page={page}/>}</main></div>
}

function Login({onLogin,theme,setTheme}){const [u,setU]=useState('authority.demo'),[p,setP]=useState('FoolProof@2026!'),[busy,setBusy]=useState(false),[err,setErr]=useState('');const roles=[['Admin','admin.demo','FoolProof@2026!'],['Conducting Body','authority.demo','FoolProof@2026!'],['Student 1','student01','Student@2026!'],['Student 2','student02','Student@2026!'],['Student 3','student03','Student@2026!'],['Proctor','proctor.demo','Proctor@2026!'],['Reviewer','reviewer.demo','Reviewer@2026!'],['Evaluator','evaluator.demo','Evaluator@2026!']];async function submit(e){e.preventDefault();setBusy(true);setErr('');try{onLogin(await api('/auth/login',{method:'POST',body:JSON.stringify({username:u,password:p})}))}catch(x){setErr(x.message)}finally{setBusy(false)}}return <div className="login-page"><div className="login-grid"><section className="hero-card"><div className="brand big"><div className="logo"><ShieldCheck size={26}/></div><div>FoolProof<span>Exam Integrity Platform</span></div></div><h1>Examinations engineered around <em>integrity</em>, resilience and evidence.</h1><p>Centre-based secure examinations with offline continuity, question chain-of-custody, per-question telemetry, auditable events and fair human review.</p><div className="hero-pills"><span><LockKeyhole size={15}/> Secure Client</span><span><WifiOff size={15}/> Offline resilient</span><span><Activity size={15}/> Evidence trail</span></div></section><section className="login-card"><button className="theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={17}/>:<Moon size={17}/>}</button><h2>Sign in</h2><p className="muted">Use a seeded demo identity for the hackathon walkthrough.</p><form onSubmit={submit}><label>Username<input value={u} onChange={e=>setU(e.target.value)}/></label><label>Password<input type="password" value={p} onChange={e=>setP(e.target.value)}/></label>{err&&<div className="error-box">{err}</div>}<button className="primary-btn" disabled={busy}>{busy?'Signing in…':'Enter platform'}<ChevronRight size={18}/></button></form><div className="demo-logins"><div className="section-title">Demo identities</div>{roles.map(r=><button key={r[1]} className="login-chip" onClick={()=>{setU(r[1]);setP(r[2])}}><span>{r[0]}</span><small>{r[1]}</small></button>)}</div></section></div></div>}

function Sidebar({session,page,setPage,logout,theme,setTheme}){const role=session.user.role;const items=role==='CANDIDATE'?[['overview','Overview',LayoutDashboard],['exam','My Exam',BookOpen],['result','Result',FileText]]:role==='PROCTOR'||role==='REVIEWER'?[['overview','Monitoring',Activity],['review','Review Queue',AlertTriangle],['audit','Audit Trail',FileText]]:role==='EVALUATOR'?[['overview','Evaluation',FileText]]:[['overview','Control Center',LayoutDashboard],['exams','Examinations',BookOpen],['people','People',Users],['audit','Audit Trail',FileText],['settings','Security',ServerCog]];return <aside className="sidebar"><div className="brand"><div className="logo"><ShieldCheck size={22}/></div><div>FoolProof<span>Integrity Platform</span></div></div><nav>{items.map(([id,name,Icon])=><button className={page===id?'nav-item active':'nav-item'} key={id} onClick={()=>setPage(id)}><Icon size={18}/><span>{name}</span></button>)}</nav><div className="sidebar-bottom"><div className="status-pill"><span className="dot"></span> Platform healthy</div><button className="nav-item" onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}<span>{theme==='dark'?'Light mode':'Dark mode'}</span></button><button className="nav-item" onClick={logout}><LogOut size={18}/><span>Sign out</span></button></div></aside>}
function Topbar({session}){return <header className="topbar"><div><div className="eyebrow">{session.user.role}</div><h3>{session.user.full_name}</h3></div><div className="top-actions"><span className="secure-badge"><ShieldCheck size={16}/> Secure session</span><span className="avatar">{session.user.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span></div></header>}

function AdminAuthorityHome({session,page}){const [exams,setExams]=useState([]);const [selected,setSelected]=useState(null);const [form,setForm]=useState({code:'FP-CSE-001',title:'CSE Secure Semester Examination',duration_minutes:30,total_marks:20,scheduled_start:'2026-09-20T10:00',scheduled_end:'2026-09-20T10:30',assurance_level:'CRITICAL'});useEffect(()=>{api('/exams').then(setExams).catch(()=>[])},[]);const createExam=async()=>{await api('/exams',{method:'POST',body:JSON.stringify({...form,created_by:session.user.id})});setExams(await api('/exams'))};return <>{page==='overview'&&<section><PageTitle title="Control Center" subtitle="Manage examination integrity across content, candidates, sessions and results."/><div className="hero-stats"><Stat label="Active examinations" value={exams.filter(x=>x.status==='RUNNING'||x.status==='SCHEDULED').length||1} trend="Scheduled + resilient"/><Stat label="Assurance" value="CRITICAL" trend="Secure client + audit"/><Stat label="Data layer" value="MySQL" trend="Transactional source of truth"/><Stat label="Offline mode" value="READY" trend="Encrypted local checkpoints"/></div><div className="dashboard-grid"><Card title="Security model"><p>Prevent → Detect → Prove → Recover</p><div className="four-step"><span>Prevent</span><span>Detect</span><span>Prove</span><span>Recover</span></div></Card><Card title="Today's operating principle"><div className="quote">“An observation is not a violation. Evidence and policy decide.”</div><p className="muted">Normal exam behaviour such as looking down while solving is recorded as telemetry only; it cannot automatically create a misconduct case.</p></Card></div></section>}
{page==='exams'&&<section><PageTitle title="Examinations" subtitle="Create, version, schedule and lock high-stakes examination configurations."/><div className="dashboard-grid"><Card title="Create examination"><div className="form-grid">{Object.entries(form).map(([k,v])=><label key={k}>{k.replaceAll('_',' ')}<input value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="primary-btn inline" onClick={createExam}>Create / update demo exam <ChevronRight size={18}/></button></Card><Card title="Exam registry"><Table rows={exams} columns={['code','title','status','assurance_level','duration_minutes']} onSelect={setSelected}/></Card></div>{selected&&<ExamDetail exam={selected} onClose={()=>setSelected(null)}/>}</section>}
{page==='people'&&<People/>}{page==='audit'&&<Audit/>}{page==='settings'&&<SecuritySettings/>}</>}

function ExamDetail({exam,onClose}){const [detail,setDetail]=useState(null);useEffect(()=>{api('/exams/'+exam.id).then(setDetail)},[exam.id]);return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><div className="eyebrow">Exam version {exam.version_no}</div><h2>{exam.title}</h2></div><button className="icon-btn" onClick={onClose}>×</button></div>{detail&&<><div className="info-grid"><Info label="Code" value={detail.exam.code}/><Info label="Duration" value={`${detail.exam.duration_minutes} min`}/><Info label="Security" value={detail.exam.assurance_level}/><Info label="Offline" value={detail.exam.offline_resilient?'Enabled':'Disabled'}/></div><div className="section-title">Questions • {detail.questions.length}</div><div className="question-list">{detail.questions.slice(0,10).map(q=><div className="q-row" key={q.id}><b>Q{q.question_no}</b><span>{q.prompt}</span><small>{q.difficulty} • {q.marks} marks</small></div>)}</div></>}</div></div>}

function CandidateHome({session,page,setPage}){const [exams,setExams]=useState([]),[active,setActive]=useState(null),[detail,setDetail]=useState(null);useEffect(()=>{api('/exams').then(setExams).catch(()=>[])},[]);useEffect(()=>{if(active)api('/exams/'+active.id).then(setDetail)},[active]);if(page==='result')return <CandidateResult session={session}/>;if(page==='exam')return <ExamRunner session={session} exam={active||exams[0]} detail={detail}/>;return <section><PageTitle title="Candidate dashboard" subtitle="Your examination journey from readiness to verified result."/><div className="hero-stats"><Stat label="Assigned examinations" value={exams.length||1} trend="All rules preloaded"/><Stat label="Primary device" value="SECURE CLIENT" trend="Centre-based exam"/><Stat label="Offline continuity" value="ENABLED" trend="No work lost on outage"/><Stat label="Integrity model" value="EVIDENCE" trend="No misleading score"/></div><div className="dashboard-grid"><Card title="Next examination"><div className="exam-card"><div><span className="status-tag">CRITICAL ASSURANCE</span><h2>{exams[0]?.title||'CSE Secure Semester Examination'}</h2><p className="muted">Assigned centre • 20 Sep 2026 • 10:00 AM</p></div><button className="primary-btn" onClick={()=>{setActive(exams[0]);setPage('exam')}}>Open exam journey <ChevronRight size={18}/></button></div></Card><ReadinessCard/></div></section>}
function ReadinessCard(){return <Card title="Readiness checklist"><div className="check-list">{[['Secure client','Installed and ready'],['Camera','Primary camera check'],['Microphone','Audio check'],['Storage','Local encrypted checkpoint'],['Network','Online now • offline resilient'],['Environment','Centre policy loaded']].map(([a,b])=><div className="check-row" key={a}><CheckCircle2 size={18}/><div><b>{a}</b><span>{b}</span></div></div>)}</div></Card>}

function ExamRunner({session,exam,detail}){const [started,setStarted]=useState(false),[attempt,setAttempt]=useState(null),[idx,setIdx]=useState(0),[answers,setAnswers]=useState({}),[online,setOnline]=useState(navigator.onLine),[camera,setCamera]=useState(false),[events,setEvents]=useState([]),[metrics,setMetrics]=useState({}),[submitted,setSubmitted]=useState(false),[solving,setSolving]=useState(false);const videoRef=useRef(null);const questions=detail?.questions||[];const q=questions[idx];useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener('online',on);window.addEventListener('offline',off);return()=>{window.removeEventListener('online',on);window.removeEventListener('offline',off)}},[]);useEffect(()=>{if(!started||!q)return;const t=setInterval(()=>{setMetrics(m=>({...m,[q.id]:{...(m[q.id]||{}),question_id:q.id,time_spent_seconds:(m[q.id]?.time_spent_seconds||0)+1,screen_facing_seconds:(m[q.id]?.screen_facing_seconds||0)+(solving?0:1),looking_down_seconds:(m[q.id]?.looking_down_seconds||0)+(solving?1:0)}}))},1000);return()=>clearInterval(t)},[started,q?.id,solving]);useEffect(()=>{if(started&&q){setMetrics(m=>({...m,[q.id]:{...(m[q.id]||{}),question_id:q.id}}))}},[idx,started,q?.id]);async function start(){if(!exam)return;const a=await api('/attempts/start',{method:'POST',body:JSON.stringify({exam_id:exam.id,candidate_id:session.user.id})});setAttempt(a);setStarted(true);try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});if(videoRef.current){videoRef.current.srcObject=s;setCamera(true)}}catch{}}
function choose(opt){setAnswers({...answers,[q.id]:opt});setMetrics(m=>({...m,[q.id]:{...(m[q.id]||{}),question_id:q.id,time_spent_seconds:(m[q.id]?.time_spent_seconds||0)+1,screen_facing_seconds:(m[q.id]?.screen_facing_seconds||0)+1,looking_down_seconds:m[q.id]?.looking_down_seconds||0}}));}
async function goOffline(){setOnline(false);if(attempt){const event={event_type:'NETWORK_DEGRADED',severity:'TECHNICAL',description:'Connectivity lost; secure local continuation activated',occurred_at:new Date().toISOString()};setEvents(e=>[...e,event]);localStorage.setItem('fp_offline_session',JSON.stringify({attempt,answers,metrics,events:[...events,event]}));}}
async function sync(){if(!attempt)return;const payload={answers:Object.values(metrics).map(m=>({...m,selected_option:answers[m.question_id]})),events:events,status:online?'ACTIVE':'OFFLINE'};if(online)await api('/attempts/'+attempt.id+'/sync',{method:'POST',body:JSON.stringify(payload)});}
async function submit(){await sync();const canonical=JSON.stringify({answers,metrics,events,attempt:attempt.session_uuid});const cryptoObj=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical));const hash=Array.from(new Uint8Array(cryptoObj)).map(x=>x.toString(16).padStart(2,'0')).join('');if(online)await api('/attempts/'+attempt.id+'/submit',{method:'POST',body:JSON.stringify({submission_hash:hash})});else localStorage.setItem('fp_pending_submit',JSON.stringify({attempt_id:attempt.id,submission_hash:hash,payload:{answers,metrics,events}}));setSubmitted(true);}
if(!started)return <section><PageTitle title="Secure examination launch" subtitle="Centre-based high-stakes mode. No mobile secondary camera. Normal solving behaviour is not a violation."/><div className="preflight"><div className="preflight-main"><div className="secure-illustration"><ShieldCheck size={54}/></div><h2>{exam?.title}</h2><p>{exam?.duration_minutes||30} minutes • {exam?.total_marks||20} marks • Critical assurance</p><button className="primary-btn" onClick={start}>Start secure session <ChevronRight size={18}/></button></div><div className="preflight-side"><ReadinessCard/></div></div></section>;
if(submitted)return <section><PageTitle title="Submission captured" subtitle="Your answers are securely stored; final marks are released only after evaluation and integrity processing."/><div className="success-panel"><CheckCircle2 size={44}/><h2>Exam submitted</h2><p className="muted">Session {attempt?.session_uuid}</p><div className="info-grid"><Info label="Connectivity" value={online?'Online + synchronized':'Offline package queued'}/><Info label="Camera" value={camera?'Active':'Unavailable'}/><Info label="Evidence" value={`${events.length} technical / policy events`}/><Info label="Scoring" value="Pending evaluation"/></div></div></section>;
return <section><div className="exam-top"><div><div className="eyebrow">{exam.code} • Secure Client</div><h2>{exam.title}</h2></div><div className="exam-status"><span className={online?'live-dot':'offline-dot'}></span>{online?'Connected':'Offline resilient'}<span className="time-chip"><Clock3 size={15}/> 00:{String(Math.max(0,29-idx)).padStart(2,'0')}:00</span></div></div><div className="exam-layout"><div className="exam-question"><div className="q-head"><span>Question {idx+1} of {questions.length}</span><span className="telemetry-chip"><MonitorCheck size={15}/> Question telemetry active</span></div><h1>{q?.prompt||'Loading question…'}</h1><div className="options">{q&&['A','B','C','D'].map(opt=><button key={opt} className={answers[q.id]===opt?'option selected':'option'} onClick={()=>choose(opt)}><b>{opt}</b><span>{q['option_'+opt.toLowerCase()]}</span></button>)}</div><div className="exam-nav"><button className="ghost-btn" onClick={()=>setIdx(Math.max(0,idx-1))}>Previous</button><button className="ghost-btn" onClick={async()=>{if(idx<questions.length-1)setIdx(idx+1);else await submit()}}>{idx<questions.length-1?'Next':'Submit exam'}</button></div></div><aside className="exam-monitor"><div className="camera-card"><div className="camera-head"><span>Primary camera</span><span className={camera?'ok':'warn'}>{camera?'LIVE':'CHECK'}</span></div><video ref={videoRef} id="candidate-camera" autoPlay muted playsInline></video><small>Candidate-facing camera. Looking down while solving is expected and is not a violation.</small></div><div className="telemetry-card"><div className="section-title">Current question telemetry</div><Metric label="Time on question" value={`${metrics[q?.id]?.time_spent_seconds||0}s`}/><Metric label="Screen-facing observed" value={`${metrics[q?.id]?.screen_facing_seconds||0}s`}/><Metric label="Looking-down observed" value={`${metrics[q?.id]?.looking_down_seconds||0}s`}/><Metric label="Policy violations" value="0" safe/></div><button className="ghost-btn" onClick={()=>setSolving(!solving)}><Eye size={16}/> {solving?"Looking down: normal solving":"Looking at screen"}</button><small className="telemetry-note">Observational telemetry only. Looking down while solving never creates a violation.</small><button className="danger-outline" onClick={goOffline}><WifiOff size={16}/> Simulate centre network outage</button><button className="primary-outline" onClick={sync}><Wifi size={16}/> Sync checkpoint</button></aside></div></section>}

function CandidateResult({session}){const [attempts,setAttempts]=useState([]),[selected,setSelected]=useState(null);useEffect(()=>{api('/proctor/attempts').then(rows=>setAttempts(rows.filter(x=>x.username===session.user.username))).catch(()=>[])},[]);const a=selected||attempts[0];return <section><PageTitle title="Results" subtitle="Results are published only after evaluation. Download a verification-ready PDF when available."/>{a?<div className="result-grid"><Card title="Published result"><div className="result-score"><span>Final score</span><strong>{a.score??'—'}</strong><small>Score appears after evaluation</small></div><div className="info-grid"><Info label="Exam" value={a.title}/><Info label="Status" value={a.status}/><Info label="Attempt" value={a.id}/></div>{a.score!=null&&<a className="primary-btn link-btn" href={`${API}/results/${a.id}/pdf`}><Download size={17}/> Download result PDF</a>}</Card><Card title="Candidate evidence summary"><p className="muted">Per-question time and observational telemetry are retained in the attempt record. Normal looking-down behaviour is not treated as misconduct.</p></Card></div>:<div className="empty"><FileText size={42}/><h3>No published result yet</h3><p>Submit your examination first. Evaluation and integrity processing happen afterward.</p></div>}</section>}

function ProctorHome({session,page}){const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[metrics,setMetrics]=useState([]);const load=()=>api('/proctor/attempts').then(setRows).catch(()=>[]);useEffect(()=>{load();const t=setInterval(load,3000);return()=>clearInterval(t)},[]);return <>{page==='overview'&&<section><PageTitle title="Monitoring" subtitle="Observe technical state and evidence signals without turning normal exam behaviour into violations."/><div className="hero-stats"><Stat label="Sessions" value={rows.length}/><Stat label="High priority" value={rows.filter(r=>r.violation_count>0).length}/><Stat label="Technical events" value={rows.reduce((a,b)=>a+b.technical_count,0)}/><Stat label="AI score" value="N/A" trend="No automatic guilt score"/></div><Card title="Live sessions"><Table rows={rows} columns={['full_name','code','status','technical_count','anomaly_count','violation_count']} onSelect={async r=>{setSelected(r);setMetrics(await api('/attempts/'+r.id+'/question-metrics'))}}/></Card>{selected&&<Investigation attempt={selected} metrics={metrics} close={()=>setSelected(null)}/>}</section>}{page==='review'&&<ReviewQueue rows={rows}/>} {page==='audit'&&<Audit/>}</>}
function ReviewQueue({rows}){const flagged=rows.filter(r=>r.violation_count>0||r.anomaly_count>0);return <section><PageTitle title="Review Queue" subtitle="Review evidence; do not treat an AI/anomaly signal as a finding by itself."/><Card title={`${flagged.length} cases require attention`}><div className="case-list">{flagged.map(r=><div className="case-row" key={r.id}><div><b>{r.full_name}</b><span>{r.code}</span></div><strong>{r.violation_count?'VIOLATION SIGNAL':'ANOMALY SIGNAL'}</strong><button className="ghost-btn">Open evidence</button></div>)}</div></Card></section>}
function Investigation({attempt,metrics,close}){return <div className="modal-backdrop"><div className="modal wide"><div className="modal-head"><div><div className="eyebrow">Session investigation</div><h2>{attempt.full_name}</h2></div><button className="icon-btn" onClick={close}>×</button></div><div className="info-grid"><Info label="Status" value={attempt.status}/><Info label="Technical events" value={attempt.technical_count}/><Info label="Anomaly events" value={attempt.anomaly_count}/><Info label="Confirmed violation signals" value={attempt.violation_count}/></div><div className="section-title">Per-question telemetry</div><Table rows={metrics} columns={['question_no','time_spent_seconds','screen_facing_seconds','looking_down_seconds','selected_option']} /></div></div>}
function People(){return <section><PageTitle title="People & roles" subtitle="Separation of duties prevents a single account from controlling questions, proctoring and results."/><div className="role-grid">{[['Platform Admin','Security & tenant controls'],['Exam Authority','Exam, question and schedule management'],['Proctor','Live monitoring + incident intervention'],['Reviewer','Evidence adjudication'],['Evaluator','Scoring and moderation'],['Candidate','Authenticated examination session']].map(([a,b])=><Card key={a} title={a}><p className="muted">{b}</p></Card>)}</div></section>}
function SecuritySettings(){return <section><PageTitle title="Security policy" subtitle="Critical assurance configuration used by the demo examination."/><div className="role-grid">{[['Secure client','Required'],['Secondary mobile camera','Disabled'],['Centre mode','Required'],['Offline resilience','Enabled'],['Question version lock','Enabled'],['Audit hash chain','Enabled'],['Human review for consequential findings','Required'],['Per-question telemetry','Enabled']].map(([a,b])=><Card key={a} title={a}><div className="setting-value">{b}</div></Card>)}</div></section>}
function Audit(){const [rows,setRows]=useState([]);useEffect(()=>{api('/audit').then(setRows).catch(()=>[])},[]);return <section><PageTitle title="Audit Trail" subtitle="Hash-linked operational history for accountable administration and investigations."/><Card title="Latest audit events"><Table rows={rows} columns={['created_at','action','entity_type','entity_id','event_hash']}/></Card></section>}
function PageTitle({title,subtitle}){return <div className="page-title"><div><div className="eyebrow">EXAM INTEGRITY CONTROL</div><h1>{title}</h1><p>{subtitle}</p></div></div>}
function Stat({label,value,trend}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{trend}</small></div>}
function Card({title,children}){return <div className="card"><div className="card-title"><h3>{title}</h3></div>{children}</div>}
function Info({label,value}){return <div className="info"><span>{label}</span><b>{value}</b></div>}
function Metric({label,value,safe}){return <div className="metric"><span>{label}</span><b className={safe?'safe':''}>{value}</b></div>}
function Table({rows,columns,onSelect}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}{onSelect&&<th></th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i} onClick={()=>onSelect?.(r)}>{columns.map(c=><td key={c}>{String(r[c]??'—').slice(0,80)}</td>)}{onSelect&&<td><ChevronRight size={16}/></td>}</tr>)}</tbody></table></div>}

function EvaluatorHome({session,page}){const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[score,setScore]=useState(''),[done,setDone]=useState(false);useEffect(()=>{api('/proctor/attempts').then(r=>setRows(r.filter(x=>x.status==='SUBMITTED'||x.status==='RESULT_READY'||x.status==='RESULT_READY'))).catch(()=>[])},[]);async function evaluate(){if(!selected)return;await api('/evaluations/'+selected.id,{method:'POST',body:JSON.stringify({evaluator_id:session.user.id,final_score:Number(score),notes:'Demo evaluation completed by evaluator.'})});setDone(true);setRows(await api('/proctor/attempts'));}return <section><PageTitle title="Evaluation & Results" subtitle="Objective scoring happens after submission; publication is a separate, auditable step."/><div className="dashboard-grid"><Card title="Submitted attempts"><Table rows={rows} columns={['full_name','code','status','submitted_at','score']} onSelect={setSelected}/></Card><Card title="Evaluate selected attempt">{selected?<><div className="info-grid"><Info label="Candidate" value={selected.full_name}/><Info label="Attempt" value={selected.id}/><Info label="Status" value={selected.status}/><Info label="Current score" value={selected.score??'Pending'}/></div><label>Final score<input value={score} onChange={e=>setScore(e.target.value)} placeholder="e.g. 17"/></label><button className="primary-btn inline" onClick={evaluate}>Save evaluation</button>{done&&<><div className="success-mini">Evaluation stored. Result remains a separate publication action.</div><button className="ghost-btn" onClick={async()=>{await api('/results/'+selected.id+'/publish',{method:'POST',body:JSON.stringify({actor_id:session.user.id})});setRows(await api('/proctor/attempts'))}}>Publish result</button></>}</>:<p className="muted">Select a submitted attempt.</p>}</Card></div></section>}
createRoot(document.getElementById('root')).render(<App/>);
